Don't encode secret when signing request
acquia/http-hmac-postman pull request #1
Opened 2018-04-16 01:33 UTC by mansinahar

According to the Acquia HTTP HMAC spec, the secret shouldn't be base64 encoded when signing the request. https://github.com/acquia/http-hmac-spec#secret-key

2018-04-16 13:46 UTC, jfarrell approved these changes

2018-04-17 00:04 UTC, malachy-mcconnell commented
I tried to explain some of that when Robert and I worked on this. In theory here it does not matter because we just pass the HMAC key and secret into this Postman script but some anecdotal testing suggested this script worked with Journey and/or Lift. So I approve this change, but I'm not sure how it affects those other apps. In my previous conversations with Robert I was confused as to how Journey and Lift handle the encoding (or not) of the secret.

2018-04-17 00:05 UTC, malachy-mcconnell approved these changes

2018-04-18 15:52 UTC, robert-burden requested changes
This change breaks profiles, decision and plexus api calls. I will fix it this was a regression when I transferred this script to open source.

2018-04-30 17:16 UTC, robert-burden commented
merged into 1.1.4 branch

2018-04-30 17:16 UTC, closed without merging

2018-05-01 16:51 UTC, mansinahar commented
Thanks @robert-burden 👍